import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, FileKey2, Link2, X } from "lucide-react";
import { keccak256, toBytes } from "viem";
import { explorerHref } from "../components/ExplorerShell";
import { useStore } from "../state";
import { agentName, CATEGORY_KEYS, CATEGORY_NAMES, native } from "../lib/format";
import { txUrl } from "../lib/config";

export function DecisionView({ hash }: { hash: string }) {
  const {cfg,agents,receipts}=useStore(); const receipt=receipts.find(r=>r.metaHash.toLowerCase()===hash.toLowerCase());
  const [record,setRecord]=useState<{kind:"loading"|"missing"|"verified"|"mismatch"|"error";data?:any;message?:string;since?:string}>({kind:"loading"});
  useEffect(()=>{if(!receipt||!cfg?.decisionLedgerUrl)return;let stop=false;fetch(`${cfg.decisionLedgerUrl}/decisions/${receipt.metaHash.toLowerCase()}`).then(async r=>{if(r.status===404){let since:string|undefined;try{since=(await r.json()).retainedSince}catch{}return setRecord({kind:"missing",since});}if(!r.ok)throw new Error(`Ledger returned ${r.status}`);const raw=await r.text();if(stop)return;setRecord(keccak256(toBytes(raw)).toLowerCase()===receipt.metaHash.toLowerCase()?{kind:"verified",data:JSON.parse(raw)}:{kind:"mismatch"});}).catch(e=>!stop&&setRecord({kind:"error",message:e.message}));return()=>{stop=true}},[receipt,cfg]);
  if(!receipt)return <div className="not-found"><strong>Decision not found in this network’s indexed history.</strong><p>Check the selected chain or wait for history backfill.</p><a href={explorerHref("/decisions",cfg?.network)}>Back to decisions</a></div>;
  const agent=agents.find(a=>a.id===receipt.agentId); const url=cfg?txUrl(cfg,receipt.txHash):null;
  return <><a className="back-link" href={explorerHref("/decisions",cfg?.network)}><ArrowLeft size={15}/>All decisions</a><section className="decision-hero"><div className={`decision-glyph purpose-bg-${CATEGORY_KEYS[receipt.category]}`}><FileKey2/></div><div><span className="eyebrow">SETTLED DECISION</span><h1>{receipt.metaHash.slice(0,18)}…</h1><p>{new Date(receipt.timestamp).toLocaleString()} · {cfg?.label}</p></div><span className="state-badge live"><Check size={12}/>Settled</span></section>
  <section className="decision-grid"><article><span className="eyebrow">PAYMENT</span><div className="decision-amount">{native(receipt.amount,cfg?.symbol,6)}</div><dl><div><dt>Agent</dt><dd><a href={explorerHref(`/agents/${receipt.agentId}`,cfg?.network)}>{agent?agentName(agent.id,agent.metadataURI):`Agent #${receipt.agentId}`}</a></dd></div><div><dt>Purpose</dt><dd><span className={`purpose purpose-${CATEGORY_KEYS[receipt.category]}`}>{CATEGORY_NAMES[receipt.category]}</span></dd></div><div><dt>Payee</dt><dd className="break-all">{receipt.payee}</dd></div><div><dt>Epoch spend after</dt><dd>{native(receipt.epochSpentAfter,cfg?.symbol,6)}</dd></div></dl></article><article><span className="eyebrow">ON-CHAIN PROOF</span><dl><div><dt>Transaction</dt><dd className="break-all">{receipt.txHash}</dd></div><div><dt>Block</dt><dd>{url?<a href={url} target="_blank" rel="noreferrer">{receipt.blockNumber.toString()} <ArrowUpRight size={12}/></a>:receipt.blockNumber.toString()}</dd></div><div><dt>Decision commitment</dt><dd className="break-all">{receipt.metaHash}</dd></div><div><dt>Epoch</dt><dd>{receipt.epoch.toString()}</dd></div></dl></article></section>
  <section className="record-section"><div className="section-heading"><div><span className="eyebrow">PUBLISHED EXPLANATION</span><h2>Decision record</h2></div>{record.kind==="verified"?<span className="verify-state good"><Check/>Hash matches</span>:record.kind==="mismatch"?<span className="verify-state bad"><X/>Hash mismatch</span>:null}</div>
  {record.kind==="loading"?<div className="record-state">Retrieving the explanation bound to this payment…</div>:record.kind==="missing"?<div className="record-state"><Link2/><div><strong>Record not published</strong><p>{record.since?`This host has kept records since ${new Date(record.since).toLocaleString()} — its last deploy; earlier records were not retained. `:""}The on-chain hash still binds any explanation published later.</p></div></div>:record.kind==="verified"?<div className="record-detail"><div><span>Action</span><strong>{String(record.data.action??"Unspecified")}</strong></div><div><span>Rationale</span><strong>{String(record.data.rationale??"No rationale field")}</strong></div>{record.data.model&&<div><span>Model</span><strong>{String(record.data.model)}</strong></div>}{record.data.inputs&&<pre>{JSON.stringify(record.data.inputs,null,2)}</pre>}</div>:<div className="record-state"><X/><div><strong>{record.kind==="mismatch"?"Published bytes do not match the commitment":"Ledger unavailable"}</strong><p>{record.message}</p></div></div>}</section></>;
}
