import { useEffect, useState } from "react";
import { ArrowUpRight, Check, CircleDot, Database, Radio } from "lucide-react";
import { CHAINS, loadConfig, type AppConfig } from "../lib/config";
import { useStore } from "../state";

type Net = AppConfig & {key:string; history?:any};
export function NetworksView(){const {cfg}=useStore();const [nets,setNets]=useState<Net[]>([]);useEffect(()=>{let stop=false;(async()=>{const rows=await Promise.all(CHAINS.map(async c=>{const conf=await loadConfig(c.key);let history:any=null;try{const base=import.meta.env.VITE_EXPLORER_API||conf.decisionLedgerUrl;if(base){const r=await fetch(`${base}/v1/explorer/${c.key}/receipts`,{signal:AbortSignal.timeout(7000)});if(r.ok)history=await r.json()}}catch{}return {...conf,key:c.key,history}}));if(!stop)setNets(rows)})();return()=>{stop=true}},[]);
return <><section className="page-intro compact"><div><span className="eyebrow">MULTICHAIN DEPLOYMENTS</span><h1>Networks</h1><p>Each governor owns separate agents, balances and history. The same agent number on two chains is not the same account.</p></div></section>
<section className="network-grid">{nets.map(n=>{const selected=n.chainId===cfg?.chainId;const status=n.history?.status;return <article className={selected?"selected":""} key={n.chainId}><div className="network-card-top"><span className={`network-orb chain-${n.network}`}/><div><strong>{n.label??n.network}</strong><span>Chain {n.chainId}</span></div>{selected&&<span className="selected-chip"><Check/>Selected</span>}</div><dl><div><dt>Governor</dt><dd title={n.contracts.Quaestor}>{n.contracts.Quaestor.slice(0,10)}…{n.contracts.Quaestor.slice(-6)}</dd></div><div><dt>Native unit</dt><dd>{n.symbol}</dd></div><div><dt>Deployment block</dt><dd>{n.startBlock.toLocaleString()}</dd></div><div><dt>Indexed head</dt><dd>{status?.indexedHead?.toLocaleString()??"Awaiting explorer API"}</dd></div></dl><div className="network-card-foot"><span className={status&&!status.error?"health good":"health pending"}><CircleDot/>{status&&!status.error?"Indexer responding":"Configured"}</span><a href={`#/app/networks?chain=${n.key}`}>Explore <ArrowUpRight/></a></div></article>})}</section>
<section className="infrastructure-strip"><div><Radio/><span><strong>Hedera testnet</strong>x402 settlement rail · HBAR</span></div><div><Database/><span><strong>The Graph</strong>Base Sepolia spend-shape index</span></div></section>
<section className="network-note"><h2>Identity across chains</h2><p>An agent is identified by <code>chain ID + governor address + agent ID</code>. Arc and Base intentionally share a governor address, but their state and history remain independent.</p></section></>}
